#!/bin/sh

# Run the instance: CentOS 7.3 x64
# Returns: InstanceId
aws ec2 run-instances --image-id ami-8e2c9aee --security-group-ids sg-966bf7ee --count 1 --instance-type t2.micro --key-name devenv-key --query 'Instances[0].InstanceId'
