#!/bin/sh
# This script should be executed on Windows host under Cygwin to
# modify Windows hosts file with IP of running AWS instance with tag Name
# got from $INST_TAG or provided in the 1st parameter.
# It requires sudo command to elevate privilegies to update Windows hosts file.
# sudo is the shell script containing: nircmd.exe elevatecmd execmd "$@"

HOSTS_WIN=/cygdrive/c/Windows/System32/drivers/etc/hosts
HOSTS_TMP=/tmp/hosts

if [ -n "$1" ]
then
  INST_TAG="$1"
fi
echo "Instance Tag Name: $INST_TAG"

INST_ID=$(aws ec2 describe-instances \
  --query "Reservations[*].Instances[?Tags[?Value==\`$INST_TAG\`]].[InstanceId,State.Name]" \
  --output text | awk '/running/{print $1}')

if [ $? -ne 0 -o -z "$INST_ID" ]
then
  echo "ERROR: getting Instance ID failed"
  exit 1
else
  echo "Instance ID: $INST_ID"
fi

if ! IP=`ec2-inst-get-ip $INST_ID` || test "$IP" = "None"
then
  echo "ERROR: getting Instantce public IP failed"
  exit 1
else
  echo "Instance public IP: $IP"
fi

awk -v IP="$IP" -v INST_TAG="$INST_TAG" '
{
  INST_TAG = tolower (INST_TAG)
  if ($0 ~ INST_TAG)
  {
    split ($0, a, "[ \t]")
    print IP "\t" a[2]
  }
  else
    print
}' "$HOSTS_WIN" > "$HOSTS_TMP"

if sudo cp "$HOSTS_TMP" "$HOSTS_WIN"
then
  awk -v INST_TAG="$INST_TAG" '
  {
    INST_TAG = tolower (INST_TAG)
    if ($0 ~ INST_TAG)
    {
      print "Windows hosts file updated:"
      print
    }
  }' "$HOSTS_WIN"
  rm -f "$HOSTS_TMP"
fi
