#!/bin/sh
# This script should be executed on Windows host under Cygwin to
# modify Windows hosts file with IP of AWS instance "mydevenv".
# It requires sudo command to elevate privilegies for updating Windows hosts file.
# sudo is the shell script containing: nircmd.exe elevatecmd execmd "$@"

HOSTS_WIN=/cygdrive/c/Windows/System32/drivers/etc/hosts
HOSTS_TMP=/tmp/hosts

IP=`ec2-inst-get-ip $@`

if [ "$IP" == "None" ]
then
  echo "ERROR: no IP address"
  exit 1
fi

cat "$HOSTS_WIN" | awk -v IP="$IP" '
{
  if (/mydevenv/)
  {
    split ($0, a, "[ \t]")
    print IP "\t" a[2]
  }
  else
    print
}' > "$HOSTS_TMP"

if sudo cp "$HOSTS_TMP" "$HOSTS_WIN"
then
  echo "IP address updated:"
  grep mydevenv $HOSTS_WIN
  rm "$HOSTS_TMP"
fi
